import { useCallback, useState, useSyncExternalStore } from 'react';

import {
  ISSUE_RESOURCE_TYPES,
  fetchAiResources,
  requestAiResources,
  type GenerationStatus,
  type IssueResourceType,
} from './api/ai-resources';
import {
  issueErrorCodeOf,
  registerCard,
  toCard,
  type IssueErrorCode,
} from './api/registrations';
import {
  fetchMockAiResources,
  registerMockCard,
  requestMockAiResources,
} from './mock/registrations';
import { useCards } from './cards-store';
import type { Card } from './types';

/**
 * The issuance, from a scanned token to a card wearing its artwork.
 *
 * **The run lives in this module, not in the screen.** Registration is one round trip, but the
 * artwork behind it is generated by a service the app only reaches by asking again, and that
 * asking must survive the screen: a customer who backgrounds the app mid-generation should come
 * back to a finished card, not to a request that died with a React unmount. So each token owns a
 * run in the map below, the screen subscribes to it, and unmounting drops the subscription rather
 * than the work. Re-entering the same token re-attaches to the run already in flight.
 *
 * Nothing above this file knows whether any of it was real — flip `USE_MOCK` and the screens do
 * not change.
 */
const USE_MOCK = true;

/** How often we ask. Fast enough that resources land visibly one after another. */
const POLL_MS = 800;
/** When we stop claiming this is nearly done and offer a way out. */
const PATIENCE_MS = 20_000;
/** When we stop asking. The card exists either way; the artwork can catch up on the server. */
const MAX_MS = 90_000;

export type IssueStage = 'registering' | 'generating' | 'ready' | 'error';

/** The three states a tile can be in. `REJECTED` is a failure to the customer, so it reads as one. */
export type ResourceState = { type: IssueResourceType; status: 'PENDING' | 'COMPLETED' | 'FAILED' };

export type IssueState = {
  stage: IssueStage;
  card: Card | null;
  resources: ResourceState[];
  /**
   * Generation has outrun the customer's patience. The screen stops holding them here — the work
   * continues on the server and the card collects it whenever it finishes.
   */
  slow: boolean;
  errorCode: IssueErrorCode | null;
};

type Run = {
  state: IssueState;
  listeners: Set<() => void>;
  /** Set when the screen is done with this token — polling stops at the next tick. */
  disposed: boolean;
  /** The card reaches the store exactly once, even if the screen mounts twice. */
  issued: boolean;
  onIssued: (card: Card) => void;
};

const runs = new Map<string, Run>();

const initialState = (): IssueState => ({
  stage: 'registering',
  card: null,
  resources: ISSUE_RESOURCE_TYPES.map((type) => ({ type, status: 'PENDING' })),
  slow: false,
  errorCode: null,
});

function patch(run: Run, next: Partial<IssueState>) {
  run.state = { ...run.state, ...next };
  run.listeners.forEach((listener) => listener());
}

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

const toResourceState = (status: GenerationStatus): ResourceState['status'] =>
  status === 'COMPLETED' ? 'COMPLETED' : status === 'PENDING' ? 'PENDING' : 'FAILED';

const settled = (resources: ResourceState[]) => resources.every((r) => r.status !== 'PENDING');

async function drive(token: string, run: Run) {
  let card: Card;
  try {
    card = USE_MOCK ? registerMockCard(token) : toCard(await registerCard(token));
  } catch (e) {
    patch(run, { stage: 'error', errorCode: issueErrorCodeOf(e) });
    return;
  }

  // The card exists on the server the moment registration returns, so it enters the collection
  // now rather than at the end: artwork is what the customer waits for, not the card.
  if (!run.issued) {
    run.issued = true;
    run.onIssued(card);
  }
  patch(run, { stage: 'generating', card });

  try {
    if (USE_MOCK) requestMockAiResources(card.id);
    else await requestAiResources(card.id, ISSUE_RESOURCE_TYPES);
  } catch {
    // A card without generated artwork is still a card — it falls back to the template's own
    // front and back. Failing to ask is not a reason to fail the issuance.
  }

  const startedAt = Date.now();

  while (!run.disposed) {
    await sleep(POLL_MS);
    if (run.disposed) return;

    try {
      const raw = USE_MOCK ? fetchMockAiResources(card.id) : await fetchAiResources(card.id);
      const resources = ISSUE_RESOURCE_TYPES.map<ResourceState>((type) => {
        const match = raw.find((r) => r.resourceType === type);
        return { type, status: match ? toResourceState(match.generationStatus) : 'PENDING' };
      });
      patch(run, { resources });

      if (settled(resources)) {
        patch(run, { stage: 'ready' });
        return;
      }
    } catch {
      // A dropped poll is not a failed generation. Keep asking until the clock says otherwise.
    }

    const elapsed = Date.now() - startedAt;
    if (elapsed > PATIENCE_MS && !run.state.slow) patch(run, { slow: true });
    if (elapsed > MAX_MS) {
      patch(run, { stage: 'ready', slow: true });
      return;
    }
  }
}

function startRun(token: string, onIssued: (card: Card) => void): Run {
  const existing = runs.get(token);
  if (existing) {
    existing.onIssued = onIssued;
    return existing;
  }

  const run: Run = {
    state: initialState(),
    listeners: new Set(),
    disposed: false,
    issued: false,
    onIssued,
  };
  runs.set(token, run);
  void drive(token, run);
  return run;
}

/**
 * Subscribes the screen to the run for `token`, starting one if this is the first look.
 *
 * `retry` throws the run away and begins again, which is only ever offered for failures the
 * customer can do nothing about — a template that is not ready, or a connection that dropped.
 * Retrying an already-spent token would just spend it again.
 */
export function useIssue(token: string) {
  const { addCard } = useCards();
  const [run, setRun] = useState(() => startRun(token, addCard));

  const subscribe = useCallback(
    (listener: () => void) => {
      run.listeners.add(listener);
      return () => run.listeners.delete(listener);
    },
    [run],
  );

  const getSnapshot = useCallback(() => run.state, [run]);
  const state = useSyncExternalStore(subscribe, getSnapshot, getSnapshot);

  const retry = useCallback(() => {
    const previous = runs.get(token);
    if (previous) previous.disposed = true;
    runs.delete(token);
    setRun(startRun(token, addCard));
  }, [token, addCard]);

  return { ...state, retry };
}
