import { Stack, useLocalSearchParams, useRouter } from 'expo-router';
import { AlertCircle, Clock, ScanLine, Wifi } from 'lucide-react-native';
import type { ComponentType } from 'react';
import { useEffect } from 'react';
import { BackHandler, Platform, StyleSheet, View } from 'react-native';

import { IssueCard } from '@/components/issue/issue-card';
import { Checklist } from '@/components/ui/checklist';
import { Button } from '@/components/ui/button';
import { Screen } from '@/components/ui/screen';
import { Text } from '@/components/ui/text';
import { RESOURCE_LABELS } from '@/lib/api/ai-resources';
import { isIssueBlocked, type IssueErrorCode } from '@/lib/api/registrations';
import { formatPurchaseDate } from '@/lib/format';
import { useIssue } from '@/lib/issue-flow';
import type { Card } from '@/lib/types';
import { colors } from '@/theme/colors';
import { radius } from '@/theme/radius';
import { space } from '@/theme/spacing';

/**
 * The issuance.
 *
 * Registration is one round trip and then the screen waits, and **the waiting is the screen** —
 * artwork is generated by a service that answers 202 and hangs up, so the only honest thing to
 * show is what is being made and how far along each piece is. A spinner here would be a shrug.
 *
 * The customer is held for the duration on purpose: this is the emotional core of the product and
 * it is a few seconds long. The hold is not a trap, though — the card is already in the collection
 * by the time generation starts, generation continues on the server whatever this screen does, and
 * the moment the wait outlasts its welcome (`slow`) a way out appears.
 */
export default function IssueScreen() {
  const params = useLocalSearchParams<{ token: string | string[] }>();
  const token = (Array.isArray(params.token) ? params.token[0] : params.token) ?? '';
  const { stage, card, resources, slow, errorCode, retry } = useIssue(token);

  const holding = stage === 'registering' || (stage === 'generating' && !slow);

  // Android's back gesture is the one way out of a screen with no back button, so it is closed
  // for exactly as long as the screen is holding and opened again the moment it is not.
  useEffect(() => {
    if (Platform.OS !== 'android') return;
    const subscription = BackHandler.addEventListener('hardwareBackPress', () => holding);
    return () => subscription.remove();
  }, [holding]);

  return (
    <Screen>
      <Stack.Screen options={{ headerShown: false, gestureEnabled: !holding }} />

      {stage === 'error' ? (
        <IssueError code={errorCode ?? 'UNKNOWN'} onRetry={retry} />
      ) : stage === 'ready' && card ? (
        <IssueReady card={card} incomplete={resources.some((r) => r.status !== 'COMPLETED')} />
      ) : stage === 'generating' && card ? (
        <IssueGenerating card={card} resources={resources} slow={slow} />
      ) : (
        <IssueRegistering />
      )}
    </Screen>
  );
}

/** Short, and usually invisible — but the shape of the card is already there, so nothing jumps. */
function IssueRegistering() {
  return (
    <View style={styles.body}>
      <IssueCard card={null} />
      <Text variant="title" style={styles.headline}>
        카드를 발급하는 중입니다
      </Text>
      <Text variant="body" tone="muted" style={styles.support}>
        영수증 코드를 확인하고 있습니다.
      </Text>
    </View>
  );
}

function IssueGenerating({
  card,
  resources,
  slow,
}: {
  card: Card;
  resources: ReturnType<typeof useIssue>['resources'];
  slow: boolean;
}) {
  const router = useRouter();
  const done = resources.filter((r) => r.status !== 'PENDING').length;

  return (
    <View style={styles.page}>
      <View style={styles.body}>
        <IssueCard card={card} />
        <Text variant="title" style={styles.headline}>
          카드 디자인을 만드는 중입니다
        </Text>
        <Text variant="body" tone="muted" style={styles.support}>
          {`${done}/${resources.length} 완료`}
        </Text>
      </View>

      <View style={styles.checklist}>
        {/* 무엇을 만들고 있는지 아는 것은 이 화면의 일이다 — `Checklist` 는 줄만 그린다. */}
        <Checklist
          items={resources.map((r) => ({
            key: r.type,
            label: RESOURCE_LABELS[r.type],
            status: r.status === 'COMPLETED' ? 'done' : r.status === 'FAILED' ? 'failed' : 'pending',
          }))}
        />
        {slow ? (
          <>
            <Text variant="caption" tone="muted" style={styles.note}>
              예상보다 오래 걸리고 있습니다. 생성은 계속 진행되며, 완료되면 카드에 반영됩니다.
            </Text>
            <Button
              label="나중에 확인하기"
              variant="outline"
              style={styles.cta}
              onPress={() => router.replace('/')}
            />
          </>
        ) : null}
      </View>
    </View>
  );
}

function IssueReady({ card, incomplete }: { card: Card; incomplete: boolean }) {
  const router = useRouter();

  return (
    <View style={styles.page}>
      <View style={styles.body}>
        <IssueCard card={card} />
        {/* The one display-sized line in the app: this is the moment the product exists for. */}
        <Text variant="display" style={styles.headline}>
          발급 완료
        </Text>
        <Text variant="body" tone="muted" style={styles.support}>
          {`${card.store.name} · ${formatPurchaseDate(card.purchaseDate)}`}
        </Text>
        {incomplete ? (
          <Text variant="caption" tone="muted" style={styles.note}>
            일부 디자인은 아직 생성 중입니다. 완료되면 카드에 반영됩니다.
          </Text>
        ) : null}
      </View>

      <View style={styles.footer}>
        <Button label="컬렉션에서 보기" onPress={() => router.replace('/')} />
        <Button
          label="계속 스캔하기"
          variant="outline"
          style={styles.cta}
          onPress={() => router.replace('/scan')}
        />
      </View>
    </View>
  );
}

/**
 * Four codes, four different situations.
 *
 * They are laid out one per case rather than behind a shared "발급에 실패했습니다" because the
 * only useful part of a failure is what to do next, and here that is four different things: look
 * at the receipt again, look in the collection, ask the store, or wait for someone else to fix it.
 * A single screen with a single button would make the customer work that out themselves.
 */
type ErrorCopy = {
  icon: ComponentType<{ size?: number; color?: string }>;
  title: string;
  /**
   * 제목이 다 말하지 못한 것만. **없을 수 있고, 없으면 그 줄을 그리지 않는다** — 이미 쓴
   * 영수증처럼 제목 한 줄과 버튼 두 개로 상황과 갈 곳이 모두 정해지는 경우, 설명은 같은 말을
   * 한 번 더 하는 자리가 된다.
   */
  body?: string;
  primary: { label: string; action: 'retry' | 'scan' | 'collection' };
  secondary?: { label: string; action: 'retry' | 'scan' | 'collection' };
};

/**
 * 화면이 실제로 가르는 경우들.
 *
 * 오류 코드는 아홉 개지만 화면은 다섯이다. 발급이 막히는 다섯 코드(템플릿 없음·비활성·타입
 * 불일치·브랜드 불일치·비활성 상품)는 전부 브랜드 쪽 설정 문제이고 고객이 할 수 있는 일이
 * 같아서, `BLOCKED` 하나로 모인다 — 다섯 개의 사과문을 쓰는 대신 하나를 정확히 쓴다.
 */
type ErrorCase = 'QR_TOKEN_INVALID' | 'QR_ALREADY_USED' | 'QR_EXPIRED' | 'BLOCKED' | 'UNKNOWN';

const ERROR_COPY: Record<ErrorCase, ErrorCopy> = {
  QR_TOKEN_INVALID: {
    icon: ScanLine,
    title: '인식할 수 없는 코드입니다',
    body: '영수증에 인쇄된 QR 코드가 맞는지 확인한 뒤 다시 시도해주세요.',
    primary: { label: '다시 스캔하기', action: 'scan' },
  },
  QR_ALREADY_USED: {
    icon: AlertCircle,
    title: '이미 발급된 영수증입니다',
    primary: { label: '컬렉션에서 보기', action: 'collection' },
    secondary: { label: '다른 영수증 스캔하기', action: 'scan' },
  },
  QR_EXPIRED: {
    icon: Clock,
    title: '발급 기한이 지났습니다',
    body: '카드를 발급할 수 있는 기간이 끝난 영수증입니다. 구매하신 매장에 문의해주세요.',
    primary: { label: '다른 영수증 스캔하기', action: 'scan' },
  },
  BLOCKED: {
    icon: Clock,
    title: '카드 디자인을 준비 중입니다',
    body: '이 상품의 카드가 아직 등록되지 않았습니다. 영수증에는 문제가 없으니 잠시 후 다시 시도해주세요.',
    primary: { label: '다시 시도하기', action: 'retry' },
    secondary: { label: '컬렉션으로 가기', action: 'collection' },
  },
  UNKNOWN: {
    icon: Wifi,
    title: '연결에 실패했습니다',
    body: '네트워크 상태를 확인한 뒤 다시 시도해주세요. 영수증은 아직 사용되지 않았습니다.',
    primary: { label: '다시 시도하기', action: 'retry' },
    secondary: { label: '컬렉션으로 가기', action: 'collection' },
  },
};

const errorCase = (code: IssueErrorCode): ErrorCase =>
  isIssueBlocked(code) ? 'BLOCKED' : (code as ErrorCase);

function IssueError({ code, onRetry }: { code: IssueErrorCode; onRetry: () => void }) {
  const router = useRouter();
  const copy = ERROR_COPY[errorCase(code)];
  const Icon = copy.icon;

  const run = (action: ErrorCopy['primary']['action']) => {
    if (action === 'retry') onRetry();
    else if (action === 'scan') router.replace('/scan');
    else router.replace('/');
  };

  return (
    <View style={styles.page}>
      <View style={styles.body}>
        <View style={styles.badge}>
          <Icon size={28} color={colors.text} />
        </View>
        <Text variant="title" style={styles.headline}>
          {copy.title}
        </Text>
        {copy.body ? (
          <Text variant="body" tone="muted" style={styles.support}>
            {copy.body}
          </Text>
        ) : null}
      </View>

      <View style={styles.footer}>
        <Button label={copy.primary.label} onPress={() => run(copy.primary.action)} />
        {copy.secondary ? (
          <Button
            label={copy.secondary.label}
            variant="outline"
            style={styles.cta}
            onPress={() => run(copy.secondary!.action)}
          />
        ) : null}
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  page: { flex: 1 },
  body: { flex: 1, justifyContent: 'center', paddingVertical: space[5] },
  headline: { marginTop: space[5], textAlign: 'center' },
  support: { marginTop: space[2], textAlign: 'center' },
  note: { marginTop: space[4], textAlign: 'center' },
  checklist: { paddingBottom: space[5] },
  footer: { paddingBottom: space[5] },
  cta: { marginTop: space[3] },
  badge: {
    width: 64,
    height: 64,
    borderRadius: radius.full,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
});
